FROM node AS builder

WORKDIR /sdow

COPY website/package.json website/package-lock.json ./
RUN npm ci --legacy-peer-deps

COPY website/src ./src
COPY website/public ./public
COPY website/firebase.json ./

ARG APP_PREFIX="http://localhost:5000/"
ARG SDOW_API_URL="http://localhost:3000/"
ARG WIKIPEDIA_API_URL="https://en.wikipedia.org/w/api.php" 
ARG WIKIPEDIA_BASE_URL="https://en.wikipedia.org/wiki/"
ARG WIKIPEDIA_API_USERAGENT="Six Degrees of Wikipedia/1.0 (https://www.sixdegreesofwikipedia.com/; wenger.jacob@gmail.com)"
ENV APP_PREFIX="$APP_PREFIX" SDOW_API_URL="$SDOW_API_URL" WIKIPEDIA_API_URL="$WIKIPEDIA_API_URL" WIKIPEDIA_BASE_URL="$WIKIPEDIA_BASE_URL" WIKIPEDIA_API_USERAGENT="$WIKIPEDIA_API_USERAGENT"
RUN npm run build


FROM nginx

WORKDIR /usr/share/nginx/html

ARG APP_FOLDER="./"
COPY --from=builder /sdow/build /usr/share/nginx/html/$APP_FOLDER

COPY nginx.conf /etc/nginx/nginx.conf

